const getRoutesResponseMock = {
    pageMeta: {
      totalPages: 20,
      page: 7,
      totalResults: 100,
      pageSize: 2,
    },
    routes: [
      {
        id: 1,
        status: 'Inactive',
        takeOff: '03:00',
        capacity: 8,
        batch: 'E',
        comments: 'dvdvdvdvdvv.',
        inUse: 4,
        name: 'Gdvdvdvdvth',
        destination: '89772 Hilpert Cove',
        driverName: 'Ludvdvdvbs',
        driverPhoneNo: '692.7444499.6133',
        regNumber: 'APP 519 DT',
      },
      {
        id: 2,
        status: 'active',
        takeOff: '04:00',
        capacity: 8,
        batch: 'D',
        comments: 'Ipsum discdc molestiae.',
        inUse: 0,
        name: 'Ga22h',
        destination: 'efvdvdvd',
        driverName: 'Luke Hobcdvdvbs',
        driverPhoneNo: '69552.799.6133',
        regNumber: 'APPscs5 519 DT',
      },
      {
        id: 3,
        status: 'active',
        takeOff: '05:00',
        capacity: 6,
        batch: 'A',
        comments: 'molestiae.',
        inUse: 1,
        name: 'Path',
        destination: 'dvdvdvdv ve',
        driverName: 'Hobbs',
        driverPhoneNo: '692.799.61553',
        regNumber: 'APscscP 519 DTttt',
        },
        {
          id: 4,
          status: 'Inactive',
          takeOff: '03:60',
          capacity: 8,
          batch: 'E',
          comments: 'dvdv molestiae.',
          inUse: 0,
          name: 'yledvdvth',
          destination: 'dvdv897dvdvdv72  Cove',
          driverName: 'Le Hodvdvbbs',
          driverPhoneNo: '692.7959.6133',
          regNumber: 'APscsc5P 519 DT',
        },
        {
          id: 5,
          status: 'Inactive',
          takeOff: '04:00',
          capacity: 8,
          batch: 'P',
          comments: 'Ipdvdvdvsue.',
          inUse: 5,
          name: 'Garr',
          destination: '89dvvdvdv7ve',
          driverName: 'Lukbs',
          driverPhoneNo: '692688133',
          regNumber: 'AP1scscdvdv9 DT',
        }
    ]
};

export default getRoutesResponseMock;
